version = "3.8.0"
runner.dialect = scala3
maxColumn = 100

align.multiline = true
align.tokens = [
  {code = "extends", owner = "Defn.(Class|Trait|Object)"}
  {code = "with", owner = "Defn.(Trait)"}
  {code = "//", owner = ".*"}
  {code = "{", owner = "Template"}
  {code = "}", owner = "Template"}
  {code = "%", owner = ".*"}
  {code = "%%", owner = ".*"}
  {code = "%%%", owner = ".*"}
  {code = "<-", owner = "Enumerator.Generator"}
  {code = "->", owner = ".*"}
  {code = "=", owner = ".*"}
  {code = "=>", owner = ".*"}
  {code = ":", owner = "Term.Param"}
]
