rules = [
  RemoveUnused
  OrganizeImports
  DisableSyntax
  NoValInForComprehension
  LeakingImplicitClassVal
]

OrganizeImports {
  groupedImports = Merge
  groups = [
    "re:javax?\\."
    "scala."
    "cats."
    "fs2."
    "io.grpc."
    "*"
  ]
}

DisableSyntax {
  noVars = true
  noThrows = true
  noNulls = true
  noReturns = true
  noAsInstanceOf = true
  noIsInstanceOf = false
  noXmlLiterals = true
  noFinalVal = false
  noFinalize = true
}

RemoveUnused {
  imports = false
  privates = true
  locals = true
  patternvars = true
}